### ISSUE TITLE
Error when trying to export ONNX from python source code

### ISSUE THREAD

**Issue by NicoleSherwood** [FeiYull/TensorRT-Alpha#4]
Hi, I am trying to export ONNX from the python source code provided in the TensorRT-Alpha project following the instructions, but I am encountering an error. The error message is as follows:

```
[ERROR] Unable to export model to ONNX format: <error message>
```

I have tried troubleshooting the issue by going through the instructions again and making sure all dependencies are installed, but the error persists. Any help would be greatly appreciated.

Steps to reproduce:

- Clone the TensorRT-Alpha repository
- Follow the instructions provided to export ONNX from the python source code
- Encounter the error above

Environment:

```
OS: Windows 10
Framework: PyTorch
TensorRT version: 7.1.3
CUDA version: 10.2
Python version: 3.7
```

Thanks!

**Comment by FeiYull** [comment]
@NicoleSherwood  hi，i guess you did not switch the training code based on tag or hash values, for example, steps are as follows：
- git clone https://github.com/ultralytics/yolov3
- git checkout  dd838e25863169d0de4f10631a609350658efb69
- download yolov3-tiny.pt
note: The above order must be strictly followed, because different tag corresponding weight files may be different
